Repository boostcamp-2020/Project01-A-User-Event-Collector, pull requests merged in 2020-12, with the labels that each got.

#77 [iOS] SearchView 생성
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Network/NetworkService.swift
  iOS/MiniVibe/MiniVibe/Scenes/DJStation/DJStationListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/MagazineView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/GenreCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/GenreListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/RectangleCellInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/RectangleCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/RectangleListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
  iOS/MiniVibe/MiniVibeTests/MiniVibeTests.swift
Labels: feat, must🔥

#78 [iOS] 앱 전반적으로 필요한 Model 구현
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/기억을 걷는 시간.imageset/Contents.json
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/나의 사춘기에게.imageset/Contents.json
  iOS/MiniVibe/MiniVibe/Common/Models/Album.swift
  iOS/MiniVibe/MiniVibe/Common/Models/Artist.swift
  iOS/MiniVibe/MiniVibe/Common/Models/Playlist.swift
  iOS/MiniVibe/MiniVibe/Common/Models/Track.swift
  iOS/MiniVibe/MiniVibe/Common/Models/User.swift
  iOS/MiniVibe/MiniVibe/Common/TestData.swift
  iOS/MiniVibe/MiniVibe/Scenes/Chart/ChartView.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/MagazineView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/Playlist.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TabBar/TabBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/Track.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackGroupView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListHeaderView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackPageView.swift
Labels: API, feat, must🔥

#80 [iOS] 검색 후에 나오는 뷰 생성
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Scenes/Search/RectangleCellInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchAfterCategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchAfterView.swift
Labels: feat, should⭐️, 검색

#82 제목: MiniVibe 전체에서 이용가능한 Type 생성
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Network/MiniVibeType.swift
  iOS/MiniVibe/MiniVibe/Common/Network/RequestBuilder.swift
  iOS/MiniVibe/MiniVibe/Common/Network/URLBuilder.swift
  iOS/MiniVibe/MiniVibe/Common/TestData.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/ThumbnailListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/ThumbnailListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/ThumbnailRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/Category.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayRouter.swift
Labels: API, feat, fix, must🔥, 공통

#84 [iOS] 네트워킹을 위한 뷰모델 분리
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Network/MiniVibeType.swift
  iOS/MiniVibe/MiniVibe/Common/Network/MiniVibeViewModel.swift
  iOS/MiniVibe/MiniVibe/Common/Network/URLBuilder.swift
  iOS/MiniVibe/MiniVibe/Common/TestData.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/MagazineView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/MagazineViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/ThumbnailListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/ThumbnailListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/ThumbnailRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchAfterCategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayRouter.swift
Labels: API, feat, fix, must🔥, 공통

#86 [iOS] 차트와 서치 뷰 네트워킹 연결
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Models/Search.swift
  iOS/MiniVibe/MiniVibe/Common/Models/Track.swift
  iOS/MiniVibe/MiniVibe/Common/Network/MiniVibeViewModel.swift
  iOS/MiniVibe/MiniVibe/Common/Network/URLBuilder.swift
  iOS/MiniVibe/MiniVibe/Scenes/Chart/ChartView.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/GenreCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/GenreListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchAfterCategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchAfterView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchAfterViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TabBar/TabBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackGroupView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackHorizontalListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
Labels: API, 검색

#87 Swiftlint 추가 및 적용
  .gitignore
  iOS/MiniVibe/.swiftlint.yml
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe.xcworkspace/contents.xcworkspacedata
  iOS/MiniVibe/MiniVibe.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/MiniVibe/MiniVibe/Common/Extension/Sequence+indexed.swift
  iOS/MiniVibe/MiniVibe/Common/Image/ActivityIndicatorView.swift
  iOS/MiniVibe/MiniVibe/Common/Image/ImageLoader.swift
  iOS/MiniVibe/MiniVibe/Common/Models/Magazine.swift
  iOS/MiniVibe/MiniVibe/Common/Network/MiniVibeViewModel.swift
  iOS/MiniVibe/MiniVibe/Common/Network/RequestBuilder.swift
  iOS/MiniVibe/MiniVibe/Common/TestData.swift
  iOS/MiniVibe/MiniVibe/Scenes/Chart/ChartView.swift
  iOS/MiniVibe/MiniVibe/Scenes/DJStation/DJStationListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/DJStation/DJStationListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/ThumbnailCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/ThumbnailListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/ThumbnailListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/GenreCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/Category/Category.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/Category/CategoryCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/Category/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackGroupView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListButtonView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListViewModel.swift
  iOS/MiniVibe/Podfile
  iOS/MiniVibe/Podfile.lock
Labels: Pair Programming

#93 [iOS] Search 화면 수정
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchAfterViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/RectangleCellInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/RectangleCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/SearchAfterView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/SearchBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/SearchBeforeView.swift
Labels: fix

#92 [iOS] AsyncImage 메모리 누수 문제 수정
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024 – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x – 2-1.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x – 2-1.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x – 2-1.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x – 2.png
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/appIcon.imageset/Contents.json
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/appIcon.imageset/appIcon.png
  iOS/MiniVibe/MiniVibe/Common/CustomView/MemorySafeNavigationLink.swift
  iOS/MiniVibe/MiniVibe/Common/Extension/Image+accesoryModifier.swift
  iOS/MiniVibe/MiniVibe/Common/Extension/Sequence+indexed.swift
  iOS/MiniVibe/MiniVibe/Common/Image/AsyncImage.swift
  iOS/MiniVibe/MiniVibe/Common/Image/ImageCacheKey.swift
  iOS/MiniVibe/MiniVibe/Common/Image/ImageLoader.swift
  iOS/MiniVibe/MiniVibe/Common/Image/TemporaryImageCache.swift
  iOS/MiniVibe/MiniVibe/Common/Image/URLImage.swift
  iOS/MiniVibe/MiniVibe/Common/Image/URLImageLoader.swift
  iOS/MiniVibe/MiniVibe/Common/Network/MiniVibeViewModel.swift
  iOS/MiniVibe/MiniVibe/Common/Network/NetworkService.swift
  iOS/MiniVibe/MiniVibe/Scenes/Magazine/MagazineView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Thumbnail/ThumbnailCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Thumbnail/ThumbnailListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Thumbnail/ThumbnailListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryHeaderView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/BasicRowCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackHorizontalListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackListHeaderView.swift
Labels: API, fix, 공통

#99 [FE] 큰 틀에서 스타일링 적용
  frontend/components/Button/HoverEllipsisButton/index.tsx
  frontend/components/ChartSlider/ChartTrackCard/index.tsx
  frontend/components/ChartSlider/index.tsx
  frontend/components/GenreContainer/index.tsx
  frontend/components/HotMagCard/index.tsx
  frontend/components/HotMagCard/styled.ts
  frontend/components/HoverImg/TrackCardHoverCover/index.tsx
  frontend/components/Layout/styled.ts
  frontend/components/NavBar/LinkCardBlock/LinkCard/styled.ts
  frontend/components/NavBar/NavBarUser/index.tsx
  frontend/components/NavBar/NavBarUser/styled.ts
  frontend/components/NavBar/index.tsx
  frontend/components/NavBar/styled.ts
  frontend/components/Slidebar/index.tsx
  frontend/pages/chart/index.tsx
  frontend/pages/today/index.tsx
Labels: FE, style

#102 [FE] Slidebar 구현 수정, css 적용
  backend/app.ts
  frontend/components/Slidebar/index.tsx
Labels: FE, style

#101 [iOS] 이벤트 수집을 위한 시스템 구현
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Event/AnalyticsEngine.swift
  iOS/MiniVibe/MiniVibe/Common/Event/AnalyticsEvent.swift
  iOS/MiniVibe/MiniVibe/Common/Event/AnalyticsManager.swift
  iOS/MiniVibe/MiniVibe/Common/Event/PlayerEvent.swift
  iOS/MiniVibe/MiniVibe/Common/Event/ScreenEvent.swift
  iOS/MiniVibe/MiniVibe/Common/Network/NetworkService.swift
  iOS/MiniVibe/MiniVibe/Common/TestData/TestData.swift
  iOS/MiniVibe/MiniVibe/MiniVibeApp.swift
  iOS/MiniVibe/MiniVibe/Scenes/Chart/ChartView.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerControlView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerHeaderView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/ToggleableImage.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TabBar/CustomTabView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TabBar/TabBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/Podfile.lock
Labels: 이벤트

#103 [FE] feat: 검색창에 엔터 버튼 누를 때 검색창으로 이동
  frontend/components/NavBar/NavTopLogoSearch/index.tsx
  frontend/components/SearchBar/index.tsx
Labels: FE, feat

#105 [iOS] Track 관련 뷰, 뷰모델, 모델 정리
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/CustomView/Accessory/EllipsisAssessory.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Accessory/HeartAccessory.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/BasicRowCellView.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Image/ActivityIndicatorView.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Image/URLImage.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Image/URLImageLoader.swift
  iOS/MiniVibe/MiniVibe/Common/Event/PlayerEvent.swift
  iOS/MiniVibe/MiniVibe/Common/TestData/TestData.swift
  iOS/MiniVibe/MiniVibe/CoreData/MiniVibe.xcdatamodeld/MiniVibe.xcdatamodel/contents
  iOS/MiniVibe/MiniVibe/MiniVibeApp.swift
  iOS/MiniVibe/MiniVibe/Models/Track.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TabBar/CustomTabView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TabBar/TabIconView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackCellViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackGroupView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackPageView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListViewModel.swift
Labels: fix, 트랙리스트

#106 [BE] fix: search api 수정
  backend/controllers/public/search/getAlbums.ts
  backend/controllers/public/search/getAll.ts
  backend/controllers/public/search/getArtists.ts
  backend/controllers/public/search/getTracks.ts
  backend/controllers/public/search/index.ts
  backend/models/tracks/getTrackForSearch.ts
  backend/models/tracks/index.ts
  backend/routes/public/search/index.ts
  backend/utils/makePrismaObtion.ts
Labels: BE, feat, fix

#108 [FE] 매거진 페이지 types 클릭마다 배경색상변경
  frontend/components/MagLabel/MagLabel.interface.ts
  frontend/components/MagLabel/index.tsx
  frontend/pages/magazines/index.tsx
Labels: FE, style

#109 [FE] Search 페이지들 구현
  backend/controllers/public/auth/naver/callbackProcess.ts
  backend/controllers/public/search/index.ts
  backend/models/tracks/getTrackForSearch.ts
  frontend/components/Button/SlidebarButton/index.tsx
  frontend/components/ChartSlider/ChartTrackCard/index.tsx
  frontend/components/ChartSlider/index.tsx
  frontend/components/ChartSlider/styled.ts
  frontend/components/GenreContainer/GenreCard/index.tsx
  frontend/components/GenreContainer/index.tsx
  frontend/components/HotMagCard/index.tsx
  frontend/components/HotMagCard/styled.ts
  frontend/components/Layout/Overlay.tsx
  frontend/components/Layout/index.tsx
  frontend/components/Layout/styled.ts
  frontend/components/MagLabel/MagLabel.style.ts
  frontend/components/NavBar/LinkCardBlock/LinkCard/styled.ts
  frontend/components/NavBar/NavBarUser/styled.ts
  frontend/components/NavBar/NavTopLogoSearch/styled.ts
  frontend/components/NavBar/index.tsx
  frontend/components/NavBar/styled.ts
  frontend/components/Playbar/index.tsx
  frontend/components/Playbar/styled.ts
  frontend/components/SearchBar/index.tsx
  frontend/components/SearchBar/styled.ts
  frontend/components/SearchSamples/albums/index.tsx
  frontend/components/SearchSamples/albums/styled.ts
  frontend/components/SearchSamples/all/index.tsx
  frontend/components/SearchSamples/all/styled.ts
  frontend/components/SearchSamples/artists/index.tsx
  frontend/components/SearchSamples/artists/styled.ts
  frontend/components/SearchSamples/tracks/index.tsx
  frontend/components/SearchSamples/tracks/styled.ts
  frontend/components/Slidebar/index.tsx
  frontend/components/Slidebar/styled.ts
  frontend/constant/icons.tsx
  frontend/pages/chart/index.tsx
  frontend/pages/magazines/index.tsx
  frontend/pages/search/albums/index.tsx
  frontend/pages/search/albums/styled.ts
  frontend/pages/search/artists/index.tsx
  frontend/pages/search/artists/styled.ts
  frontend/pages/search/index.tsx
  frontend/pages/search/styled.ts
  frontend/pages/search/tracks/index.tsx
  frontend/pages/search/tracks/styled.ts
  frontend/pages/today/index.tsx
Labels: FE, feat, style

#111 [FE] 체크박스 -> 체크된 트랙 -> 플레이 바, Redux를 이용한 상태 변경
  frontend/components/DetailPage/DetailButtonBox/index.tsx
  frontend/components/DetailPage/DetailHeader/index.tsx
  frontend/components/DetailPage/index.tsx
  frontend/components/Layout/index.tsx
  frontend/components/Playbar/index.tsx
  frontend/components/Tracklist/TrackCard/CheckBox/index.tsx
  frontend/components/Tracklist/TrackCard/TrackModal/index.tsx
  frontend/components/Tracklist/TrackCard/index.tsx
  frontend/components/Tracklist/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/_document.js
  frontend/pages/albums/[pid].tsx
  frontend/pages/artists/[pid].tsx
  frontend/pages/magazines/[pid].tsx
  frontend/pages/playlists/[pid].tsx
  frontend/reduxModules/allCheck/index.ts
  frontend/reduxModules/checkedTrack/index.ts
  frontend/reduxModules/index.ts
  frontend/reduxModules/playQueue/index.ts
Labels: FE, feat

#117 [iOS] coredata 기능 및 보관함 기능 추가
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/CustomView/BasicRowCellView.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Image/ImageCache.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Image/URLImage.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Image/URLImageLoader.swift
  iOS/MiniVibe/MiniVibe/Common/Network/CacheService.swift
  iOS/MiniVibe/MiniVibe/Common/Reachability/ReachabilityObserverDelegate.swift
  iOS/MiniVibe/MiniVibe/Common/TestData/TestData.swift
  iOS/MiniVibe/MiniVibe/CoreData/ContentView.swift
  iOS/MiniVibe/MiniVibe/CoreData/MiniVibe.xcdatamodeld/MiniVibe.xcdatamodel/contents
  iOS/MiniVibe/MiniVibe/CoreData/Model/CoreTrackAPI.swift
  iOS/MiniVibe/MiniVibe/CoreData/Persistence.swift
  iOS/MiniVibe/MiniVibe/MiniVibeApp.swift
  iOS/MiniVibe/MiniVibe/Models/Album.swift
  iOS/MiniVibe/MiniVibe/Models/Artist.swift
  iOS/MiniVibe/MiniVibe/Models/Track.swift
  iOS/MiniVibe/MiniVibe/Scenes/Library/LibraryViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/SearchAfterCategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/SearchBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Thumbnail/ThumbnailListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Thumbnail/ThumbnailRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackCellViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackHorizontalListView.swift
Labels: feat, fix, must🔥

#118 [FE] Mongo DB 설정
  backend/app.ts
  backend/controllers/public/log/iOS.ts
  backend/controllers/public/log/index.ts
  backend/controllers/public/log/web.ts
  backend/mongo.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/public/index.ts
  backend/routes/public/log/index.ts
Labels: API, BE, DB, feat

#120 [iOS] coredata 세부 사항 수정
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/CustomView/Image/URLImageLoader.swift
  iOS/MiniVibe/MiniVibe/Common/TestData/TestData.swift
  iOS/MiniVibe/MiniVibe/CoreData/API/CoreTrackAPI.swift
  iOS/MiniVibe/MiniVibe/CoreData/API/Metadatable.swift
  iOS/MiniVibe/MiniVibe/CoreData/MiniVibe.xcdatamodeld/MiniVibe.xcdatamodel/contents
  iOS/MiniVibe/MiniVibe/CoreData/Persistence.swift
  iOS/MiniVibe/MiniVibe/Models/Album.swift
  iOS/MiniVibe/MiniVibe/Models/Artist.swift
  iOS/MiniVibe/MiniVibe/Models/Track.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerInfoView.swift
Labels: API, must🔥

#119 [FE/BE] refactor: DB와 통신 방식 변경 및 Track Card 변경
  backend/models/albums/getById.ts
  backend/models/artists/getById.ts
  backend/models/magazines/getById.ts
  backend/models/news/getById.ts
  backend/models/playlists/getById.ts
  backend/models/tracks/getTrackForSearch.ts
  frontend/components/DescriptionHeader/index.tsx
  frontend/components/DescriptionHeader/styled.ts
  frontend/components/DetailPage/DetailHeader/index.tsx
  frontend/components/DetailPage/index.tsx
  frontend/components/DetailPage/styled.ts
  frontend/components/Layout/Overlay.tsx
  frontend/components/Layout/PlaylistCheckBar.styled.ts
  frontend/components/Layout/PlaylistCheckBar.tsx
  frontend/components/Layout/index.tsx
  frontend/components/Layout/styled.ts
  frontend/components/Playbar/index.tsx
  frontend/components/SearchBar/index.tsx
  frontend/components/SearchSamples/all/index.tsx
  frontend/components/TrackCard/index.tsx
  frontend/components/TrackCard/styled.ts
  frontend/constant/icons.tsx
  frontend/event/event.tsx
  frontend/interfaces/index.ts
  frontend/pages/albums/[pid].tsx
  frontend/pages/artists/[pid].tsx
  frontend/pages/magazines/[pid].tsx
  frontend/pages/magazines/index.tsx
  frontend/pages/news/[pid].tsx
  frontend/pages/playlists/[pid].tsx
  frontend/pages/search/albums/index.tsx
  frontend/pages/search/artists/index.tsx
  frontend/pages/search/index.tsx
  frontend/pages/search/styled.ts
  frontend/pages/search/tracks/index.tsx
  frontend/pages/today/index.tsx
Labels: BE, FE, feat, refactor, style

#126 [BE] feat: Mongo에 저장된 로그를 받아올 수 있는 API 생성
  backend/controllers/public/log/iOS.ts
  backend/controllers/public/log/index.ts
  backend/controllers/public/log/web.ts
  backend/routes/public/log/index.ts
  frontend/components/Layout/PlaylistCheckBar.tsx
  frontend/components/Layout/index.tsx
  frontend/components/TrackCard/index.tsx
  frontend/components/Tracklist/TrackCard/CheckBox/index.tsx
  frontend/reduxModules/checkedTrack/index.ts
  frontend/reduxModules/playQueue/index.ts
Labels: BE, feat

#127 [FE] feat: 플레이바와 재생 목록의 중앙화
  frontend/components/DetailPage/DetailButtonBox/index.tsx
  frontend/components/Layout/Overlay.tsx
  frontend/components/Layout/PlaylistCheckBar.styled.ts
  frontend/components/Layout/PlaylistCheckBar.tsx
  frontend/components/Layout/index.tsx
  frontend/components/Layout/styled.ts
  frontend/components/Playbar/index.tsx
  frontend/components/Playbar/styled.ts
  frontend/components/TrackCard/index.tsx
  frontend/components/Tracklist/TrackCard/CheckBox/index.tsx
  frontend/components/Tracklist/TrackCard/TrackModal/TrackModalLayout/index.tsx
  frontend/components/Tracklist/TrackCard/TrackModal/index.tsx
  frontend/components/Tracklist/TrackCard/index.stories.tsx
  frontend/components/Tracklist/TrackCard/index.tsx
  frontend/components/Tracklist/index.tsx
  frontend/reduxModules/allCheck/index.ts
  frontend/reduxModules/checkedTrack/index.ts
  frontend/reduxModules/index.ts
  frontend/reduxModules/playQueue/index.ts
Labels: FE, feat, style

#129 [iOS] 이벤트 로그를 화면에 보여주는 기능 추가
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Event/AlertAnalyticsEngine.swift
  iOS/MiniVibe/MiniVibe/Common/Event/AnalyticsEvent.swift
  iOS/MiniVibe/MiniVibe/Common/Event/AnalyticsManager.swift
  iOS/MiniVibe/MiniVibe/Common/Event/ButtonEvent.swift
  iOS/MiniVibe/MiniVibe/Common/Event/PlayerEvent.swift
  iOS/MiniVibe/MiniVibe/Common/Event/ScreenEvent.swift
  iOS/MiniVibe/MiniVibe/Common/Extension/Date+StringForWeb.swift
  iOS/MiniVibe/MiniVibe/Common/Image/ActivityIndicatorView.swift
  iOS/MiniVibe/MiniVibe/Common/Image/ImageCache.swift
  iOS/MiniVibe/MiniVibe/Common/Image/SwappableImageLoaderAndCache.swift
  iOS/MiniVibe/MiniVibe/Common/Image/SwappableImageWithURL.swift
  iOS/MiniVibe/MiniVibe/Common/Image/URLImage.swift
  iOS/MiniVibe/MiniVibe/Common/Image/URLImageLoader.swift
  iOS/MiniVibe/MiniVibe/Info.plist
  iOS/MiniVibe/MiniVibe/MiniVibeApp.swift
  iOS/MiniVibe/MiniVibe/Scenes/Chart/ChartView.swift
  iOS/MiniVibe/MiniVibe/Scenes/DJStation/DJStationListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Library/LibraryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Thumbnail/ThumbnailListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackHorizontalListView.swift
Labels: Pair Programming, fix, must🔥, should⭐️, 이벤트

#131 [iOS] 순환참조로 인한 메모리 누수 수정
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Image/ActivityIndicatorView.swift
  iOS/MiniVibe/MiniVibe/Common/Image/SwappableImageLoaderAndCache.swift
  iOS/MiniVibe/MiniVibe/Common/Image/SwappableImageWithURL.swift
  iOS/MiniVibe/MiniVibe/Common/Image/URLImageLoader.swift
  iOS/MiniVibe/MiniVibe/Common/Network/URLBuilder.swift
  iOS/MiniVibe/MiniVibe/Common/Reachability/ReachabilityObserverDelegate.swift
  iOS/MiniVibe/MiniVibe/Common/Test/DeallocPrinter.swift
  iOS/MiniVibe/MiniVibe/Common/Test/TestData.swift
  iOS/MiniVibe/MiniVibe/MiniVibeApp.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerControlView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/ToggleableImage.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/TabBar/TabIconView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Thumbnail/ThumbnailListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Thumbnail/ThumbnailRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryItem.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackCellViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackListButtonView.swift
Labels: fix, must🔥

#135 [iOS] 검색을 위한 모델 정리 및 플레이어뷰에서 트랙 삭제 기능을 추가
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/CustomView/Accessory/DeleteAccessory.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Accessory/DownloadAccessory.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Accessory/EllipsisAccessory.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Accessory/HeartAccessory.swift
  iOS/MiniVibe/MiniVibe/Common/Test/TestData.swift
  iOS/MiniVibe/MiniVibe/CoreData/API/CoreTrackAPI.swift
  iOS/MiniVibe/MiniVibe/CoreData/MappingModelV2ToV3.xcmappingmodel/xcmapping.xml
  iOS/MiniVibe/MiniVibe/CoreData/MiniVibe.xcdatamodeld/.xccurrentversion
  iOS/MiniVibe/MiniVibe/CoreData/MiniVibe.xcdatamodeld/MiniVibe v3.xcdatamodel/contents
  iOS/MiniVibe/MiniVibe/MiniVibeApp.swift
  iOS/MiniVibe/MiniVibe/Models/Album.swift
  iOS/MiniVibe/MiniVibe/Models/Artist.swift
  iOS/MiniVibe/MiniVibe/Models/Track.swift
  iOS/MiniVibe/MiniVibe/Scenes/Library/LibraryViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/SearchAfterCategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackCellViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackHorizontalListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
Labels: PlayerView, must🔥

#138 [iOS] 이벤트 로깅 마무리
  iOS/MiniVibe/MiniVibe/Common/Event/ButtonEvent.swift
  iOS/MiniVibe/MiniVibe/Common/Event/PlayerEvent.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerControlView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/GenreCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/GenreListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/RectangleCellInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/RectangleCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/RectangleListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/SearchBeforeView.swift
Labels: feat, must🔥, 이벤트

#141 [iOS] 앱 전반적으로 버그 수정 및 리팩토링
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/기억을 걷는 시간.imageset/Contents.json
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/기억을 걷는 시간.imageset/기억을 걷는 시간.jpg
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/나의 사춘기에게.imageset/Contents.json
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/나의 사춘기에게.imageset/나의 사춘기에게.jpg
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/우산.imageset/Contents.json
  iOS/MiniVibe/MiniVibe/Common/Assets.xcassets/images/우산.imageset/우산.jpg
  iOS/MiniVibe/MiniVibe/Common/CustomView/Accessory/DeleteAccessory.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Accessory/DownloadAccessory.swift
  iOS/MiniVibe/MiniVibe/Common/CustomView/Accessory/EllipsisAccessory.swift
  iOS/MiniVibe/MiniVibe/Common/Image/SwappableImageWithURL.swift
  iOS/MiniVibe/MiniVibe/Common/Test/TestData.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/AnalyticsManager.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Engines/AlertAnalyticsEngine.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Engines/AnalyticsEngine.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Engines/BackupAnalyticsEngine.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Engines/MockServerEngine.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Engines/MongoDBEngine.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Events/AnalyticsEvent.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Events/ButtonEvent.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Events/PlayerEvent.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Events/ScreenEvent.swift
  iOS/MiniVibe/MiniVibe/DiveEventCollector/Views/LoggableButton.swift
  iOS/MiniVibe/MiniVibe/Scenes/Chart/ChartView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Library/LibraryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerControlView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerHeaderView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/PlayerInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/SwipableImageView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/SubViews/ToggleableImage.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SearchView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/RectangleCellInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/RectangleCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/SearchBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Search/SubViews/SearchBeforeView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Thumbnail/ThumbnailListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/SubViews/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/SubViews/TrackHorizontalListView.swift
Labels: Pair Programming, fix, refactor

#149 [FE] (feat/style): 스타일 수정 및 로컬 로그인 기능 추가
  backend/controllers/auth/index.ts
  backend/controllers/auth/local/login.ts
  backend/controllers/auth/local/signup.ts
  backend/routes/auth/index.ts
  frontend/components/Layout/styled.ts
  frontend/components/NavBar/NavBarUser/index.tsx
  frontend/components/NavBar/NavBarUser/styled.ts
  frontend/components/NavBar/NavTopLogoSearch/index.tsx
  frontend/components/NavBar/NavTopLogoSearch/styled.ts
  frontend/constant/icons.tsx
  frontend/event/SequencedEventObserver.ts
  frontend/event/collector.tsx
  frontend/event/emitter.tsx
  frontend/event/index.ts
  frontend/event/interface.ts
  frontend/pages/auth/login.tsx
  frontend/pages/auth/signup.tsx
  frontend/pages/magazines/[pid].tsx
  frontend/pages/news/[pid].tsx
  frontend/pages/playlists/[pid].tsx
Labels: FE, feat, refactor, style
