Repository boostcamp-2020/Project01-A-User-Event-Collector, pull requests merged in 2020-11, with the labels that each got.

#35 [iOS] TrackListView 구현
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Models/Track.swift
  iOS/MiniVibe/MiniVibe/ViewModels/TrackListViewModel.swift
  iOS/MiniVibe/MiniVibe/Views/AccessoryViews/EllipsisAccessoryView.swift
  iOS/MiniVibe/MiniVibe/Views/AccessoryViews/HeartAccessoryView.swift
  iOS/MiniVibe/MiniVibe/Views/TrackCell.swift
  iOS/MiniVibe/MiniVibe/Views/TrackListView.swift
Labels: 투데이, 트랙리스트

#37 [iOS] Today 페이지 구현
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Today/Category.swift
  iOS/MiniVibe/MiniVibe/Today/CategoryInfoView.swift
  iOS/MiniVibe/MiniVibe/Today/CategoryItem.swift
  iOS/MiniVibe/MiniVibe/Today/CategoryItemView.swift
  iOS/MiniVibe/MiniVibe/Today/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Today/TodayView.swift
Labels: must🔥, should⭐️, 공통, 투데이

#41 [iOS] Playlist 구현
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Extension/Sequence+indexed.swift
  iOS/MiniVibe/MiniVibe/Playlist/Playlist.swift
  iOS/MiniVibe/MiniVibe/Playlist/PlaylistCellView.swift
  iOS/MiniVibe/MiniVibe/Playlist/PlaylistListView.swift
  iOS/MiniVibe/MiniVibe/Playlist/PlaylistListViewModel.swift
  iOS/MiniVibe/MiniVibe/Playlist/PlaylistRouter.swift
  iOS/MiniVibe/MiniVibe/Playlist/PlaylistView.swift
  iOS/MiniVibe/MiniVibe/Playlist/RouterProtocol.swift
  iOS/MiniVibe/MiniVibe/ViewModifier/FontStyle.swift
  iOS/MiniVibe/MiniVibe/ViewModifier/NavigationBarStyle.swift
Labels: feat, must🔥, 플레이리스트

#48 [iOS] 머지 후 파일 순서 변경 및 라우팅 수정
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/CoreData/ContentView.swift
  iOS/MiniVibe/MiniVibe/CoreData/MiniVibe.xcdatamodeld/.xccurrentversion
  iOS/MiniVibe/MiniVibe/CoreData/MiniVibe.xcdatamodeld/MiniVibe.xcdatamodel/contents
  iOS/MiniVibe/MiniVibe/CoreData/Persistence.swift
  iOS/MiniVibe/MiniVibe/MiniVibeApp.swift
  iOS/MiniVibe/MiniVibe/Scenes/DJStation/DJStation.swift
  iOS/MiniVibe/MiniVibe/Scenes/DJStation/DJStationListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/DJStation/DJStationListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/Playlist.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/RouterProtocol.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/Category.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryItem.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryItemView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/Track.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListViewModel.swift
Labels: 공통

#51 [iOS] 트랙리스트에서 하트가 흑백으로 보이는 버그 수정
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListViewModel.swift
Labels: fix

#52 [iOS] Playlist 수정 및 라우터 객체 생성
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Router/Router.swift
Labels: feat, fix, 공통, 플레이리스트

#57 [iOS] fix: 하트가 흑백에서 빨강으로 glitch되는 버그 수정
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
Labels: fix, 트랙리스트

#58 [iOS] FontStyle Title의 컬러 primary로 변경
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryInfoView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryItemView.swift
  iOS/MiniVibe/MiniVibe/ViewModifier/FontStyle.swift
Labels: fix

#59 [iOS] NavigationBarStyle .foregroundColor(.primary) 제거
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/MiniVibe/ViewModifier/NavigationBarStyle.swift
Labels: fix, must🔥, 공통, 트랙리스트

#62 [iOS] now playing 뷰와 player 뷰 구현, track과 연동
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Extension/Image+accesoryModifier.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/BlurView.swift
  iOS/MiniVibe/MiniVibe/Scenes/NowPlaying/NowPlayingView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/TabBar/TabBarView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackCellView.swift
Labels: feat, must🔥, 트랙리스트

#63 [iOS] 라우팅 방식 도입
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistListViewModel.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Router/Router.swift
  iOS/MiniVibe/MiniVibe/Scenes/Router/RouterProtocol.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/Category.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryCell.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryHeaderView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListButtonView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListHeaderView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListViewModel.swift
  iOS/MiniVibe/MiniVibe/ViewModifier/ButtonStyle.swift
  iOS/MiniVibe/MiniVibe/ViewModifier/FontStyle.swift
Labels: fix, must🔥, 공통

#72 [iOS] 전반적인 라우터 연결 및 Sticky Header 적용
  iOS/MiniVibe/MiniVibe.xcodeproj/project.pbxproj
  iOS/MiniVibe/MiniVibe/Scenes/Player/PlayerView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Playlist/PlaylistView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Router/RouterProtocol.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/Category.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/CategoryView.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayRouter.swift
  iOS/MiniVibe/MiniVibe/Scenes/Today/TodayView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackCellView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListButtonView.swift
  iOS/MiniVibe/MiniVibe/Scenes/TrackList/TrackListView.swift
  iOS/MiniVibe/MiniVibe/ViewModifier/ButtonStyle.swift
Labels: feat, fix, 공통, 플레이리스트
